services:
  postgres:
    image: "postgres:latest"
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env

volumes:
  postgres_data:
